base_url = "https://tsvldb.com"
title = "Andrii Tsvielodub"
theme = "tabi"
generate_feed = true
build_search_index = true
compile_sass = true

[markdown]
highlight_code = true
external_links_target_blank = true
smart_punctuation = true

[extra]
menu = [
    { name = "Posts", url = "posts", trailing_slash = true },
#    { name = "Projects", url = "projects", trailing_slash = true },
#    { name = "About Me", url = "about-me", trailing_slash = true },
]